# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('voting_poll', '0002_auto_20160922_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='end date')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voting_poll', related_query_name='voting_poll', to='voting_poll.Question', verbose_name='question')),
            ],
            options={
                'verbose_name_plural': 'votign polls',
                'verbose_name': 'votign poll',
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', related_query_name='answer', to='voting_poll.Question', verbose_name='question'),
        ),
    ]
