# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_poll', '0003_auto_20160927_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingpoll',
            name='end_date',
            field=models.DateTimeField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='votingpoll',
            name='start_date',
            field=models.DateTimeField(verbose_name='start date'),
        ),
    ]
